### PR TITLE
289 auth login page functionality

### LINKED ISSUE #289: auth: login page functionality
After the login page design developed in #140, we should develop the login functionality, including appropriate error messages.

Image

### PR DESCRIPTION
**Pull request by AvilaAndre**
Closes #289

Performs the request to the backend to login, showing a message if it succeeds or not and redirecting to the landing page if it does.

This pull request also includes changes to the docker compose, due to requiring access to the _localhost_ in a development environment to access the backend.

# Screenshots

# Review checklist

- [x] Contains enough appropriate tests
- [x] Behavior is as expected
- [x] Clean, well-structured code

### CODE REVIEW

**Comment by AvilaAndre** [comment]
There are none of the remaining auth methods, there is a logout in the page `/profile` which validates the auth with the backend, something like that could be used to manage session on the frontend, however, I do not know which way would be more efficient and therefore I haven't started it in this PR.

**Comment by MRita443** [comment]
@AvilaAndre Check linter pls ;(

**Comment by MRita443** [comment]
While you're at it, can you remove `version: '3'` from `docker-compose.yaml`? It's deprecated

**Review by MRita443 — APPROVED** [review]
Great job! :)

**Pull request merged**
