### PR TITLE
Fix/sidebar expansion

### LINKED ISSUE #278: bug: Fix mobile sidebar not expanding to end on scrollable pages
Currently, the mobile `Sidebar` will not expand to the end of the page if its content makes the page scrollable. We should investigate and fix the underlying issue.

Image

To replicate:

- Viewport 320x568

- **src/routes/(app)/(home)/+page.svelte**
`<div style="min-height: 400px;"></div>`

### PR DESCRIPTION
**Pull request by MRita443**
Closes #278 
Fixes the mobile sidebar not expanding to the bottom of the screen when scrolled.

# Screenshots

# Review checklist

- [ ] Contains enough appropriate tests
- [ ] Behavior is as expected
- [ ] Clean, well-structured code

### CODE REVIEW

**Comment by MRita443** [comment]
@rubuy-74 @LuisDuarte1

**Comment by MRita443** [comment]
This also fixed the background color not extending to the end on scrollable pages

**Comment by MRita443** [comment]
> This also fixed the background color not extending to the end on scrollable pages

This seems to no longer be the case with the new updates on `develop`. If I remove height: 100% from the HTML element though it works. I am not sure why and might open an issue on that

**Review by rubuy-74 — APPROVED** [review]
As discussed on the meeting, the problem will be discussed in another issue. Aside from that it is ready for merge.

**Review by rubuy-74 — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
