### PR TITLE
feat: add pull request template and github actions for testing, linti…

### LINKED ISSUE #2: ci: add github actions for tests, linting and audit
Also create a review list (PR template), dependabot

### PR DESCRIPTION
**Pull request by CarlosMealha**
closes #2

### CODE REVIEW

**Review by BrunoRosendo — CHANGES_REQUESTED** [review]
Add names to the jobs and dependabot

**Review by BrunoRosendo — APPROVED** [review]
Good job! I approve but I'll wait for another review before merging

**Review by bdmendes — CHANGES_REQUESTED** [review]
Can you remove the formatting changes? Also, I would like to see `Screenshots` as a part of the PR template, since this is a frontend repository. Otherwise, the actions look good to me.

**Comment by BrunoRosendo** [comment]
> 

Are `Screenshots` necessary when we have previews? It seems redundant but maybe it's worth it for cases where one needs to be authenticated, for example

**Comment by BrunoRosendo** [comment]
> Can you remove the formatting changes? Also, I would like to see `Screenshots` as a part of the PR template, since this is a frontend repository. Otherwise, the actions look good to me.

Also, the formatting changes might be because of the linter's rules that were not checked before. Can you confirm this @CarlosMealha ?

**Comment by bdmendes** [comment]
@BrunoRosendo I think it's easier to showcase all changes... The tester might not go through all when viewing the deploy

**Comment by CarlosMealha** [comment]
@bdmendes Okay, soI divided the commit in two, one part for the github actions and pull request template, and the other for the initial formatting of the boilerplate

**Review by bdmendes — APPROVED** [review]

**Pull request merged**
