### PR TITLE
Adds stories to all components

### LINKED ISSUE #101: storybook: add missing storybook components
There are components that do not have a storybook implementation, this issue will help us define how to structure our storybook stories as well as provide us with well documented components.

- [ ] Components should have a story, when adequate
- [ ] Stories should adequately illustrate a component's different usages

### PR DESCRIPTION
**Pull request by BrunoRosendo**
closes #101 

Finishes setting up storybook and creates stories for the current components and pages.

The book's organization was inspired by https://bradfrost.com/blog/post/atomic-design-and-storybook/ (I'll update the wiki)

# Review checklist

- [ ] Contains enough appropriate tests
- [ ] Behavior is as expected
- [ ] Clean, well-structured code

### CODE REVIEW

**Comment by BrunoRosendo** [comment]
This is mostly ready but I'm having a problem creating stories for the layout and complete pages. I'll keep you updated

**Comment by BrunoRosendo** [comment]
I currently have two problems:
- When creating stories for pages, I have to manually add the layout as a decorator (see +page.stories.ts), I don't seem to find a way to automatically include the layout on the pages.
- I can't create stories for the error pages because it imports from `$app/stores`. I tried mocking it using webpack in storybook settings with no success. I don't find anyone complaining about this error so I'm open for suggestions

**Comment by BrunoRosendo** [comment]
I removed error page's story, since I couldn't grasp a good way to handle the issue

**Comment by BrunoRosendo** [comment]
@DoStini @bdmendes please review 😢

**Review by ttoino — APPROVED** [review]

**Review by pedrosilva17 — APPROVED** [review]
Very well done!

**Pull request merged**
