### PR TITLE
theme: configure storybook

### LINKED ISSUE #7: theme: configure storybook

### PR DESCRIPTION
**Pull request by ttoino**
Closes #7.

### CODE REVIEW

**Review by BrunoRosendo — CHANGES_REQUESTED** [review]
I'm getting a `Not found: /favicon.svg` error when running storybook but it doesn't seem relevant.

Could you write something about the tool in the README? Other than that, it's just missing a rebase and LGTM! This is a nice addition

**Comment by ttoino** [comment]
I've added the command to run storybook, and a link to the relevant docs for writing new stories.

I think it's important to mention that this version of storybook is still in beta.

**Review by BrunoRosendo — APPROVED** [review]
lgtm!

**Review by limwa — APPROVED** [review]
LGTM!

**Comment by limwa** [comment]
@BrunoRosendo only authorized users can merge PRs, is this supposed to happen? To me and @ttoino, merging is blocked :pensive:

**Comment by BrunoRosendo** [comment]
> @BrunoRosendo only authorized users can merge PRs, is this supposed to happen? To me and @ttoino, merging is blocked pensive

Definitely not supposed to happen, I'm not THAT much of a dictator

**Pull request merged**
