### PR TITLE
EventHexagon component

### LINKED ISSUE #14: events: basic listing page
Create a first version for the `Events` page. Since the complete version is a big addition to the site, we can start by implementing a page with all the UI components (using what's being created in #1 ), and information retrieval but little to no user interaction. The included features would be:
- [ ] List of events, making use of the work in #1 
- [ ] Auxiliary UI components, such as title, search bar, filters and timeline (look at the mockups and screenshot below). Note that these should be reusable and added to storybook
- [ ] Mobile view for the previous points
- [ ] Retrieve events list from the backend

image

Image

### PR DESCRIPTION
**Pull request by MRita443**
Adds HexagonEvent component for use in events listing page (for demo purposes a test page was created in /routes)

# Screenshots

# Review checklist

- [x] Contains enough appropriate tests
- [x] Behavior is as expected
- [x] Clean, well-structured code

### CODE REVIEW

**Comment by MRita443** [comment]
@DoStini I tried to keep this branch up to date with `develop`, whenever you merge please update yours too

**Review by Vidal322 — APPROVED** [review]

**Comment by MRita443** [comment]
@Vidal322 @rubuy-74 @LuisDuarte1 review bump

**Review by rubuy-74 — CHANGES_REQUESTED** [review]
image image

I don't know if it's possible to see, but the interval event hexagon is larger. This could be a problem, since they are positioned side by side in the events page.

**Comment by MRita443** [comment]
> image image
> 
> I don't know if it's possible to see, but the interval event hexagon is larger. This could be a problem, since they are positioned side by side in the events page.

I tested it out and confirmed that in the grid these differences are not there
image

**Review by rubuy-74 — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
